### ISSUE TITLE
Alsa sound?

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#17] opened 2019-06-08 17:14 UTC
Is there possibility to make sound through ALSA?

**Comment by AsciiWolf** [comment] 2019-06-08 18:04
Hm, it should be working, but PulseAudio is probably the default output device.

**Comment by bam80** [comment] 2019-06-08 19:21
It doesn't work on systems w/o PulseAudio

**Comment by dreamer** [comment] 2019-07-02 12:44
I can't reproduce this problem any more, but for me sound was missing after the first install (it might've been caused by pulseaudio being updated). After restart (due to kernel update), the problem "resolved itself" on its own.

@bam80 Do you still experience sound problem with dosbox? Which game did you test?

**Comment by bam80** [comment] 2019-07-02 14:08
@dreamer did you use Alsa?
There is no problem when you have PulseAudio

UPDATE:
@BetaRays had no sound with Alsa

**Comment by BetaRays** [comment] 2019-07-03 14:27
No pulse libraries were installed either.

**Comment by dreamer** [comment] 2019-07-03 14:39
How do you reconfigure DOSBox to use plain ALSA when PulseAudio is present on the system?

**Comment by AsciiWolf** [comment] 2019-07-03 16:16
Try running DOSBox Flatpak with `--env=SDL_AUDIODRIVER=alsa`.

**Comment by AsciiWolf** [comment] 2019-07-03 16:18
However, this seems to be a Flatpak issue, not DOSBox or SDL one.

**Comment by AsciiWolf** [comment] 2019-12-31 15:46
As has been said, this does not seem to be a DOSBox issue. Closing this ticket.

**Closed as completed by AsciiWolf** 2019-12-31 15:46 UTC
